(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var g=this||self;function l(a,b){a=a.split(".");var c=g;a[0]in c||"undefined"==typeof c.execScript||c.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)a.length||void 0===b?c[d]&&c[d]!==Object.prototype[d]?c=c[d]:c=c[d]={}:c[d]=b};var m={},n=null;var p="function"===typeof Uint8Array;const q=Symbol(void 0);function r(a){Object.isFrozen(a)||(q?a[q]|=1:void 0!==a.g?a.g|=1:Object.defineProperties(a,{g:{value:1,configurable:!0,writable:!0,enumerable:!1}}));return a};function t(a){return null!==a&&"object"===typeof a&&!Array.isArray(a)&&a.constructor===Object};function w(a,b){if(null!=a){if(Array.isArray(a))a=x(a,b);else if(t(a)){const c={};for(let d in a)c[d]=w(a[d],b);a=c}else a=b(a);return a}}function x(a,b){const c=a.slice();for(let d=0;d<c.length;d++)c[d]=w(c[d],b);if(b=Array.isArray(a)){let d;q?d=a[q]:d=a.g;b=(null==d?0:d)&1}b&&r(c);return c}
function y(a){if(a&&"object"==typeof a&&a.toJSON)return a.toJSON();a:switch(typeof a){case "number":a=isFinite(a)?a:String(a);break a;case "object":if(a&&!Array.isArray(a)&&p&&null!=a&&a instanceof Uint8Array){var b;void 0===b&&(b=0);if(!n){n={};for(var c="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789".split(""),d=["+/=","+/","-_=","-_.","-_"],e=0;5>e;e++){var f=c.concat(d[e].split(""));m[e]=f;for(var h=0;h<f.length;h++){var k=f[h];void 0===n[k]&&(n[k]=h)}}}b=m[b];c=Array(Math.floor(a.length/
3));d=b[64]||"";for(e=f=0;f<a.length-2;f+=3){var u=a[f],v=a[f+1];k=a[f+2];h=b[u>>2];u=b[(u&3)<<4|v>>4];v=b[(v&15)<<2|k>>6];k=b[k&63];c[e++]=h+u+v+k}h=0;k=d;switch(a.length-f){case 2:h=a[f+1],k=b[(h&15)<<2]||d;case 1:a=a[f],c[e]=b[a>>2]+b[(a&3)<<4|h>>4]+k+d}a=c.join("")}}return Array.isArray(a)?x(a,y):a};let z;function A(a,b,c){var d=z;z=null;a||(a=d);d=this.constructor.o;a||(a=d?[d]:[]);this.i=(d?0:-1)-(this.constructor.m||0);this.l=void 0;this.g=a;a:{d=this.g.length;a=d-1;if(d&&(d=this.g[a],t(d))){this.j=a-this.i;this.h=d;break a}void 0!==b&&-1<b?(this.j=Math.max(b,a+1-this.i),this.h=void 0):this.j=Number.MAX_VALUE}if(c)for(b=0;b<c.length;b++)if(a=c[b],a<this.j)a+=this.i,(d=this.g[a])?Array.isArray(d)&&r(d):this.g[a]=B;else{d=this.h||(this.h=this.g[this.j+this.i]={});let e=d[a];e?Array.isArray(e)&&r(e):
d[a]=B}}const B=Object.freeze(r([]));function C(a,b,c=!1){return-1===b?null:b>=a.j?a.h?a.h[b]:void 0:c&&a.h&&(c=a.h[b],null!=c)?c:a.g[b+a.i]}function D(a,b){a=C(a,b);return null==a?a:!!a}function E(a){a=C(a,3);return null==a?0:a}function F(a){a=D(a,1);return null==a?!1:a}function G(a,b,c,d=!1){b<a.j&&!d?a.g[b+a.i]=c:(a.h||(a.h=a.g[a.j+a.i]={}))[b]=c}function H(a,b,c,d){c!==d?G(a,b,c):G(a,b,void 0,!1)}
function I(a,b,c){if(-1===c)return null;a.l||(a.l={});const d=a.l[c];if(d)return d;let e=C(a,c,!1);if(null==e)return d;b=new b(e);return a.l[c]=b}A.prototype.toJSON=function(){return x(this.g,y)};function J(a,b){z=b=b?JSON.parse(b):null;a=new a(b);z=null;return a}A.prototype.toString=function(){return this.g.toString()};var L=class extends A{constructor(a){super(a,-1,K)}},K=[8];var N=class extends A{constructor(a){super(a,-1,M)}},M=[17];var P=class extends A{constructor(a){super(a,-1,O)}},O=[27];var Q=class extends A{constructor(a){super(a)}};var ba=class extends A{constructor(a){super(a,-1,aa)}},aa=[1,2,3];var da=class extends A{constructor(){super(void 0,-1,ca)}},ca=[12];/*

 SPDX-License-Identifier: Apache-2.0
*/
function R(a,b){a=a.getElementsByTagName("META");for(let c=0;c<a.length;++c)if(a[c].getAttribute("name")===b)return a[c].getAttribute("content")||"";return""};function S(a){if(!(0<a.g.length)){var b=R(a.body,"environment");for(const c of b.split("|"))c&&a.g.push(c)}}function T(a,b){a=a.body;var c={detail:void 0};let d;"function"===typeof window.CustomEvent?d=new CustomEvent(b,c):(d=document.createEvent("CustomEvent"),d.initCustomEvent(b,!!c.bubbles,!!c.cancelable,c.detail));a.dispatchEvent(d)}
var ea=class{constructor(a){this.body=a;this.g=[];R(a,"sampling_mod");var b=R(a,"namespace");if(!b){b="ns-"+(0,Math.random)().toString(36).substr(2,5);a:{var c=a.getElementsByTagName("META");for(let d=0;d<c.length;++d)if("namespace"===c[d].getAttribute("name")&&c[d].getAttribute("index")===(0).toString()){c[d].setAttribute("content",b);break a}c=a.querySelector("#mys-meta");c||(c=document.createElement("div"),c.id="mys-meta",c.style.position="absolute",c.style.display="none",a.appendChild(c));a=document.createElement("META");
a.setAttribute("name","namespace");a.setAttribute("content",b);a.setAttribute("index",(0).toString());c.appendChild(a)}}S(this)}addEventListener(a,b){this.body.addEventListener(a,b)}};var fa=class extends A{constructor(){super(void 0)}};function U(a){var b=document;a=String(a);"application/xhtml+xml"===b.contentType&&(a=a.toLowerCase());return b.createElement(a)};function V(a){if(1>=a.h.offsetWidth||1>=a.h.offsetHeight)return!1;a.g.remove();T(a.context,"spanReady");return!0}
var ha=class{constructor(a,b){this.context=a;this.i=b;this.h=U("SPAN");this.g=U("DIV");this.h.style.fontSize="6px";this.h.textContent="go";this.g.style.position="absolute";this.g.style.top="100%";this.g.style.left="100%";this.g.style.width="1px";this.g.style.height="0";this.g.style.overflow="hidden";this.g.style.visibility="hidden";this.g.appendChild(this.h)}wait(){if(!F(this.i)&&(T(this.context,"spanStart"),this.context.body.appendChild(this.g),!V(this)))return new Promise(a=>{const b=setInterval(()=>
{V(this)&&(clearInterval(b),a())},E(this.i))})}};var ia=class{constructor(a,b){this.context=a;this.h=I(b,P,1);this.g=I(b,L,12)||new L;I(this.h,N,10)||new N}};var ja=class{constructor(){this.channel=3;(this.g=!(!window.mys||!window.mys.pingback))&&this.setData(43,Date.now()-window.mys.pingback.getBaseTime())}setAttribute(a,b){this.g&&window.mys.pingback.setAttribute(a,b)}setData(a,b){this.g&&window.mys.pingback.setData(a,b,this.channel)}send(a){this.g&&window.mys.pingback.send(a)}};function W(a){a.g&=-31}function X(a,b){a.g|=b}var ka=class{constructor(a,b){this.context=a;this.j=b;new da;this.g=0;this.pingback=new ja}h(){}};function Y(a){J(ba,R(a.context.body,"engine_msg")||"[]");return a.g.h()||Promise.resolve()}
var la=class{constructor(a,b,c,d){this.g=d(a,b,c);this.context=this.g.context}init(){var a;W(this.g);X(this.g,1);null===(a=window.AFMA_Communicator)||void 0===a?void 0:a.addEventListener("onshow",()=>{X(this.g,32)});let b=0;const c=this.context.body;c.addEventListener("browserRender",()=>{++b;if(1===b)T(this.context,"overallStart"),Y(this).then(()=>{T(this.context,"overallQuiet")});else{var d=c.clientHeight;c.clientWidth&&d&&Y(this)}})}};function ma(a){a.i.length=0;a.h=!0}function Z(a,b){a.g=!0;const c=()=>{a.h=!1;const d=a.i.shift();return void 0===d?(a.g=!1,Promise.resolve()):Z(a,d())};return b?b.then(c,()=>{if(a.h)return c();a.g=!1;return Promise.reject()}):c()}function na(a,b){for(const c of b)a.i.push(c);if(!a.g)return Z(a)}var oa=class{constructor(){this.h=this.g=!1;this.i=[]}};var pa=class extends ka{constructor(){super(...arguments);this.i=new oa}h(){ma(this.i);return na(this.i,[()=>{},()=>{let a;var b=this.j;const c=new fa;H(c,3,100,0);H(c,4,1E4,0);H(c,5,!0,!1);D(b.g,3)&&H(c,2,!0,!1);b=b.context;S(b);0<=b.g.indexOf("amp")&&H(c,2,!0,!1);c&&(a=(new ha(this.context,c)).wait());T(this.context,"browserStart");T(this.context,"browserStartEnd");W(this);X(this,2);return a},()=>{T(this.context,"browserReady");T(this.context,"browserReadyEnd");X(this,4);T(this.context,"overallReady")},
()=>{T(this.context,"browserQuiet");T(this.context,"browserQuietEnd");X(this,8)}])}};(function(a){let b=null;l("mys.engine.init",(c,d)=>{const e=J(Q,R(d,"render_config")||"[]");b=new la(c,d,e,a);b.init()});l("mys.engine.stage",()=>b?b.g.g:0)})(function(a,b,c){a=new ea(b);c=new ia(a,c);return new pa(a,c)});}).call(this);
