(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var g=this||self;function l(a){l[" "](a);return a}l[" "]=function(){};var m={},n=null;var aa="function"===typeof Uint8Array;const p=Symbol(void 0);function q(a){Object.isFrozen(a)||(p?a[p]|=1:void 0!==a.g?a.g|=1:Object.defineProperties(a,{g:{value:1,configurable:!0,writable:!0,enumerable:!1}}));return a};function r(a){return null!==a&&"object"===typeof a&&!Array.isArray(a)&&a.constructor===Object};function t(a,b){if(null!=a){if(Array.isArray(a))a=u(a,b);else if(r(a)){const c={};for(let d in a)c[d]=t(a[d],b);a=c}else a=b(a);return a}}function u(a,b){const c=a.slice();for(let d=0;d<c.length;d++)c[d]=t(c[d],b);if(b=Array.isArray(a)){let d;p?d=a[p]:d=a.g;b=(null==d?0:d)&1}b&&q(c);return c}
function v(a){if(a&&"object"==typeof a&&a.toJSON)return a.toJSON();a:switch(typeof a){case "number":a=isFinite(a)?a:String(a);break a;case "object":if(a&&!Array.isArray(a)&&aa&&null!=a&&a instanceof Uint8Array){var b;void 0===b&&(b=0);if(!n){n={};for(var c="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789".split(""),d=["+/=","+/","-_=","-_.","-_"],e=0;5>e;e++){var f=c.concat(d[e].split(""));m[e]=f;for(var h=0;h<f.length;h++){var k=f[h];void 0===n[k]&&(n[k]=h)}}}b=m[b];c=Array(Math.floor(a.length/
3));d=b[64]||"";for(e=f=0;f<a.length-2;f+=3){var x=a[f],y=a[f+1];k=a[f+2];h=b[x>>2];x=b[(x&3)<<4|y>>4];y=b[(y&15)<<2|k>>6];k=b[k&63];c[e++]=h+x+y+k}h=0;k=d;switch(a.length-f){case 2:h=a[f+1],k=b[(h&15)<<2]||d;case 1:a=a[f],c[e]=b[a>>2]+b[(a&3)<<4|h>>4]+k+d}a=c.join("")}}return Array.isArray(a)?u(a,v):a};let w;function z(a,b,c){var d=w;w=null;a||(a=d);d=this.constructor.u;a||(a=d?[d]:[]);this.i=(d?0:-1)-(this.constructor.s||0);this.l=void 0;this.g=a;a:{d=this.g.length;a=d-1;if(d&&(d=this.g[a],r(d))){this.j=a-this.i;this.h=d;break a}void 0!==b&&-1<b?(this.j=Math.max(b,a+1-this.i),this.h=void 0):this.j=Number.MAX_VALUE}if(c)for(b=0;b<c.length;b++)if(a=c[b],a<this.j)a+=this.i,(d=this.g[a])?Array.isArray(d)&&q(d):this.g[a]=A;else{d=this.h||(this.h=this.g[this.j+this.i]={});let e=d[a];e?Array.isArray(e)&&q(e):
d[a]=A}}const A=Object.freeze(q([]));function B(a,b,c=!1){return-1===b?null:b>=a.j?a.h?a.h[b]:void 0:c&&a.h&&(c=a.h[b],null!=c)?c:a.g[b+a.i]}function ba(a){a=B(a,16);a=null==a?a:!!a;return null==a?!1:a}function C(a,b,c){if(-1===c)return null;a.l||(a.l={});const d=a.l[c];if(d)return d;let e=B(a,c,!1);if(null==e)return d;b=new b(e);return a.l[c]=b}z.prototype.toJSON=function(){return u(this.g,v)};z.prototype.toString=function(){return this.g.toString()};var da=class extends z{constructor(a){super(a,-1,ca)}},ca=[17];var fa=class extends z{constructor(a){super(a,-1,ea)}},ea=[27];var ha=class extends z{constructor(){super(D)}};var E=document;/*

 SPDX-License-Identifier: Apache-2.0
*/
function F(){var a=G;try{var b;if(b=!!a&&null!=a.location.href)a:{try{l(a.foo);b=!0;break a}catch(c){}b=!1}return b}catch(c){return!1}}function ia(a){var b={stack:Error().stack,aswift:window.google_async_iframe_id};for(const c in b)Object.prototype.hasOwnProperty.call(b,c)&&a(b[c],c,b)}let H=[];const I=()=>{const a=H;H=[];for(const b of a)try{b()}catch(c){}};
var ja=a=>{var b=window;"complete"===b.document.readyState?(H.push(a),1==H.length&&(window.Promise?Promise.resolve().then(I):window.setImmediate?setImmediate(I):setTimeout(I,0))):b.addEventListener("load",a)};function ka(a=document){return a.createElement("img")};var ma=()=>{let a="https://pagead2.googlesyndication.com/pagead/gen_204?id=badpubwin";ia((b,c)=>{b&&(a+=`&${c}=${encodeURIComponent(b)}`)});la(a)},la=a=>{var b=window;if(b.fetch)b.fetch(a,{keepalive:!0,credentials:"include",redirect:"follow",method:"get",mode:"no-cors"});else{b.google_image_requests||(b.google_image_requests=[]);const c=ka(b.document);c.src=a;b.google_image_requests.push(c)}};var J=!!window.google_async_iframe_id;let G=J&&window.parent||window;let K=null;var L=()=>{const a=g.performance;return a&&a.now&&a.timing?Math.floor(a.now()+a.timing.navigationStart):Date.now()},M=()=>{const a=g.performance;return a&&a.now?a.now():null};class na{constructor(a,b){var c=M()||L();this.label=a;this.type=b;this.value=c;this.duration=0;this.uniqueId=Math.random();this.slotId=void 0}};const N=g.performance,oa=!!(N&&N.mark&&N.measure&&N.clearMarks),O=function(a){let b=!1,c;return function(){b||(c=a(),b=!0);return c}}(()=>{var a;if(a=oa){var b;if(null===K){K="";try{a="";try{a=g.top.location.hash}catch(c){a=g.location.hash}a&&(K=(b=a.match(/\bdeid=([\d,]+)/))?b[1]:"")}catch(c){}}b=K;a=!!b.indexOf&&0<=b.indexOf("1337")}return a});function pa(a){a&&N&&O()&&(N.clearMarks(`goog_${a.label}_${a.uniqueId}_start`),N.clearMarks(`goog_${a.label}_${a.uniqueId}_end`))}
class qa{constructor(){var a=P;this.g=[];this.i=a||g;let b=null;a&&(a.google_js_reporting_queue=a.google_js_reporting_queue||[],this.g=a.google_js_reporting_queue,b=a.google_measure_js_timing);this.h=O()||(null!=b?b:1>Math.random())}start(a,b){if(!this.h)return null;a=new na(a,b);b=`goog_${a.label}_${a.uniqueId}_start`;N&&O()&&N.mark(b);return a}end(a){if(this.h&&"number"===typeof a.value){a.duration=(M()||L())-a.value;var b=`goog_${a.label}_${a.uniqueId}_end`;N&&O()&&N.mark(b);!this.h||2048<this.g.length||
this.g.push(a)}}};if(J&&!F()){let a="."+E.domain;try{for(;2<a.split(".").length&&!F();)E.domain=a=a.substr(a.indexOf(".")+1),G=window.parent}catch(b){}F()||(G=window)}G!==window&&.01>Math.random()&&ma();const P=G,Q=new qa;var R=()=>{P.google_measure_js_timing||(Q.h=!1,Q.g!=Q.i.google_js_reporting_queue&&(O()&&Array.prototype.forEach.call(Q.g,pa,void 0),Q.g.length=0))};"number"!==typeof P.google_srt&&(P.google_srt=Math.random());
if("complete"==P.document.readyState)R();else if(Q.h){var ra=()=>{R()},S=P;S.addEventListener&&S.addEventListener("load",ra,!1)};function T(a,b){a=a.getElementsByTagName("META");for(let c=0;c<a.length;++c)if(a[c].getAttribute("name")===b)return a[c].getAttribute("content")||"";return""};function U(a){if(!(0<a.g.length)){var b=T(a.body,"environment");for(const c of b.split("|"))c&&a.g.push(c)}}function V(a,b,c){a.body.addEventListener(b,c)}function sa(a){U(a);return 0<=a.g.indexOf("amp")}
var ta=class{constructor(){var a=W;this.body=a;this.g=[];T(a,"sampling_mod");var b=T(a,"namespace");if(!b){b="ns-"+(0,Math.random)().toString(36).substr(2,5);a:{var c=a.getElementsByTagName("META");for(let d=0;d<c.length;++d)if("namespace"===c[d].getAttribute("name")&&c[d].getAttribute("index")===(0).toString()){c[d].setAttribute("content",b);break a}c=a.querySelector("#mys-meta");c||(c=document.createElement("div"),c.id="mys-meta",c.style.position="absolute",c.style.display="none",a.appendChild(c));
a=document.createElement("META");a.setAttribute("name","namespace");a.setAttribute("content",b);a.setAttribute("index",(0).toString());c.appendChild(a)}}U(this)}};var ua=class{constructor(){this.g={}}set(a,b){this.g[a]=b}get(a){return this.g[a]}};function va({threshold:a,target:b,m:c,o:d}){if(window.IntersectionObserver){var e=!1;(new IntersectionObserver(f=>{0!==f.length&&f[0].isIntersecting&&(!e&&c&&c(),e=!0,d&&d())},{threshold:a})).observe(b)}};var wa=class{constructor(){this.channel=1;(this.g=!(!window.mys||!window.mys.pingback))&&this.setData(43,Date.now()-window.mys.pingback.getBaseTime())}setAttribute(a,b){this.g&&window.mys.pingback.setAttribute(a,b)}setData(a,b){this.g&&window.mys.pingback.setData(a,b,this.channel)}send(a){this.g&&window.mys.pingback.send(a)}tick(a,b){this.g&&(this.setData(a,Date.now()-window.mys.pingback.getBaseTime()),this.send(b))}};var xa=class{constructor(a){this.context=a;this.i=new ua;this.pingback=new wa}g(){}};function ya(){var a=X,b=Y,c;sa(a.context)||(null===(c=C(C(b,fa,1),da,10))||void 0===c?0:ba(c))||(b=mys.engine?mys.engine.stage():0,0===(b&1)&&V(a.context,"overallStart",()=>{}),0!==(b&4)&&a.g.g(),V(a.context,"browserStart",()=>{}),V(a.context,"browserReady",()=>{a.g.g()}),V(a.context,"browserQuiet",()=>{}))}var Aa=class{constructor(){var a=Z;this.g=za;this.context=a}};var Ba=class extends xa{};function Ca(a){a.h||(a.h=!0,va({threshold:.9,target:document.querySelector(".x-layout"),m:()=>{const b=document.querySelector(".x-layout");b&&b.classList.add("web-on-show")}}))}var Da=class extends Ba{constructor(a){super(a);this.h=!1}g(){setTimeout(()=>{ja(()=>{Ca(this)})},0)}};var Ea=class extends Da{};const W=document.getElementById("mys-content");if(W){var Z=new ta,za;za=new Ea(Z);var X=new Aa,Fa=X.g.i,Ga=T(Z.body,"runtime_data");if(Ga){const b=JSON.parse(Ga);for(const c in b)b.hasOwnProperty(c)&&Fa.set(c,b[c])}var Y,Ha=T(Z.body,"render_config")||"[]",D=Ha?JSON.parse(Ha):null;w=D;const a=new ha;w=null;Y=a;ya()};}).call(this);
